- name: Controllo della versione minima di Contact
  hosts: "*-cti1"
  gather_facts: true
  any_errors_fatal: true
  
  vars:
    contact_minimum_version: '7.0.5-2'
    bug: 6589
    
  tasks:
  - name: controllo la versione di contact
    shell: "rpm -q cth-libs | grep {{ contact_minimum_version }}"
    check_mode: false
    failed_when: false
    changed_when: false
    register: contact_version
  
  - block:
    - fail: msg="Contact deve essere alla versione {{ contact_minimum_version }} almeno. Non posso proseguire"
    - meta: end_play
    when: contact_version.rc != 0

- name: Conferma per l'aggiornamento
  hosts: "*-cti1"
  gather_facts: true
  any_errors_fatal: true
  
  vars:
    bug: 6589
    logfile: /var/log/ansible_reitek.log
  
  tasks:
  - block:
    - name: Conferma la volontà di voler aggiornare
      pause: prompt='Per favore conferma la volontà di aggiornare Easycim alla versione 3.6.3! digita yes per proseguire. Premi Ctrl+c e poi "a" per interrompere'
      register: conferma
      when: ( AUTO is not defined or  ( AUTO is defined and AUTO != "true" )) and ansible_check_mode != true
      
    - meta: end_play
      when: not conferma.user_input == "yes"

    - name: resoconto in file {{ logfile }}
      shell: echo "Applicato il bug {{bug}} (UPGRADE_EASYCIM 3.6.3) dall'utente $USER in data $(date +%d-%m-%Y_%H:%M:%S) sui server {{inventory_hostname}} " >> {{ logfile }}
      changed_when: false

    - name: resoconto in database ansible
      shell: mysql --user=ansible_update --password=$(cat /home/password_insert) -e "insert into ansible.bugs values ( '{{bug}}','$USER','$(date +%d-%m-%Y_%H:%M:%S)','{{inventory_hostname}}');"
      changed_when: false

    delegate_to: localhost
    delegate_facts: true
    run_once: true
